# Generated by Django 5.2.8 on 2025-12-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload', '0002_discussionmessage'),
    ]

    operations = [
    ]
