# Generated by Django 5.2.8 on 2025-12-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload', '0003_auto_20251206_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionmessage',
            name='is_moderated',
        ),
    ]
