# Generated by Django 5.2.8 on 2025-12-07 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload', '0005_discussionmessage_dataset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='data_upload.discussionmessage'),
        ),
    ]
